global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'nasa_monitor'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
